### Create Stripe Checkout Session (Basic Auth)
POST https://api.stripe.com/v1/checkout/sessions
Authorization: Basic {{STRIPE_API_KEY}}
Content-Type: application/x-www-form-urlencoded

success_url=https://example.com/success
&mode=payment
&line_items[0][price]=price_1MotwRLkdIwHu7ixYcPLm5uZ
&line_items[0][quantity]=2

