server.port=9091
spring.application.name=stripeprovider

#datasource config - mysql
spring.datasource.url=jdbc:mysql://localhost:3306/payments?serverTimeZone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=exampleuser
spring.datasource.password=examplepass

#jpa config
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true


# stripe configs
# stripe.config.api.key=PASTE_STRIPE_API_KEY_HERE
# stripe.config.api.scheme=PASTE_STRIPE_SCHEME_HERE
# stripe.config.api.host=PASTE_STRIPE_API_KEY_HERE
# stripe.config.api.path.create-session=PASTE_STRIPE_API_KEY_HERE
# stripe.config.api.path.get-session=PASTE_STRIPE_API_KEY_HERE
# stripe.config.api.path.expire-session=PASTE_STRIPE_API_KEY_HERE
